# DLMTOOL OPERATING MODEL {#app:dlmtool-om}

<!-- *A summary of the important features of the DLMtool operating model* -->

<!-- *Draw on appendix of DLMtool paper but simplified to have one region* -->

<!-- *Not too many details; reference the paper* -->

<!-- *TODO: Add references to slot names for user-defined parameters. Need to decide on a consistent method. E.g., do we just put the slot name in parentheses after the parameter or say something specific like "This parameter is  defined under stock@M etc. This is potentially problematic as we are giving the stock and other objects species-specific names (e.g., stock_rex@M). We could just use rex as an example. Or we could go with something generic like stock_speciesname@M* -->

The DLMtool population dynamics operating model (OM) is an age-structured model decribed below. The OM is flexible, with options to allow a number of parameters (e.g., natural mortality, growth, selectivity) to vary through time.
Multiple sub-areas can also be described, and outcome uncertainty can be represented through the addition of implementation uncertainty and bias parameters.
A full range of possible parameterizations is described in the appendices of @carruthers2018, adapted here for the MP Framework.
Here, we present the simplest version of the OM, without time-varying parameters, multiple sub-areas, or implementation bias. 
This OM structure should be suitable as a base OM for most species intended to be assessed with the framework.
More complex structural assumptions, including time-varying parameters, could be developed as scenarios when justified for individual stocks.
Wherever possible, we follow the notation conventions used in the appendices of @carruthers2018 for consistency.

<!-- *TODO: Do we agree on these names for the milestone years??* -->

There are two distinct time-periods in the simulation framework: 
(1) The historical period, which covers the years from the first year of the catch time-series $t_1$ to the final year of the catch time series $t_c$ (where "c" represents "current"); and 
(2) the projection period, which covers the period from the first year after $t_c$ to the final projection year $t_N$. 
The historical period is calibrated to historical observations using an age-structured stock-reduction analysis (SRA) [@kimura1982; @walters2006], described in Appendix \@ref(app:sra).
The closed-loop simulations and calculation of performance metrics begin in year $t_{c+1}$.

Operating model development in the MP Framework when using DLMtool follows three steps:

1. Set parameter values and ranges in the DLMtool OM (OM equations in this appendix; default parameter settings in Appendix \@ref(app:default-slots); examples of user-defined parameter settings in Appendices \@ref(app:desc-om-rex) and \@ref(app:desc-om-sr));

2. Pass the OM parameters to the SRA model (`SRA_scope()` function in MSEtool), which conditions the OM by fitting an age-structured SRA to historical observed catches and indices of abundance (and to age- and length-composition data if available). 
This results in calibrated estimates of model parameters, and estimates of historical biomass and historical fishing mortality that are consistent with historical observations. 
Equations for the SRA model are provided in Appendix \@ref(app:sra); then

3. Pass the calibrated parameter values back to the DLMtool OM (now the "conditioned" OM) for use in the closed-loop simulation projections.

## POPULATION DYNAMICS MODEL  {#sec:dlmtool-pop-dynamics}

Parameters for the population dynamics are included in the `Stock` object of DLMtool.

### Growth and maturity

The operating model assumes that growth follows a von Bertalanffy model:

\begin{equation}
L_{y,a} = L_{\infty}\left( 1 - \exp( - \kappa(a - a_{0} \right))
(\#eq:dlm-om-vonb)
\end{equation}

where $\kappa$ represents the growth rate, $L_{\infty}$ represents the maximum length and $a_0$ represents the theoretical age where length is zero.

Weight-at-age ($W_a$) is  assumed to be related to length-at-age ($L_a$) by:

\begin{equation}
W_{y,a} = \beta_{W}\ {L_{a}}^{\alpha_{W}}.
(\#eq:dlm-om-wta)
\end{equation}

Maturity is specified according to length, using a logistic model with parameters describing length-at-50% maturity ($\theta_{l50}$) and the length increment to 95% maturity ($\theta_{l50-95}$). Maturity ($m$) at length ($l$) is then calculated as:

<!-- TODO: I might've messed this up in my interpretation of Delta l50, which is now been removed! Check this! -->

\begin{equation}
m_{l} = \frac{1}{1 + e^{{- \ln}19\left( \frac{l - \theta_{l50}}{{{\theta}}_{l50-95}} \right)}},
(\#eq:dlm-om-matl)
\end{equation}

where and maturity ($m$) at age ($a$) is calculated using the length-at-age:

\begin{equation}
m_{a} = \frac{1}{1 + e^{{- \ln}19\left( \frac{a - \theta_{a50}}{\theta_{a95} - \theta_{a50}} \right)}}
(\#eq:dlm-om-mata)
\end{equation}

where \(\theta_{a50}\) and \(\theta_{a95}\) represent the age at 50% and 95% maturity given by the inverse von-Bertalanffy growth curve:

<!-- TODO: check these! -->
\begin{equation}
\theta_{a50} = \frac{- \ln\left( 1 - \theta_{l50} / L_{\infty} \right)}{\kappa} + t_{0}
(\#eq:dlm-om-invonb)
\end{equation}

\begin{equation}
\theta_{a95} = \frac{- \ln\left( 1 - \left( \theta_{l50} / L_{\infty} + {{\theta}}_{l50\_ 95} / L_{\infty} \right) \right)}{\kappa} + t_{0}
(\#eq:dlm-om-theta95)
\end{equation}

### Population dynamics

Leading parameters of the population dynamics model, defined as fixed values or ranges by the user, are: unfished recruitment \({{R}}_{0}\), the steepness parameter of the stock-recruit relationship ($h$) [@mace1988], and natural mortality ($M$). 

Recruitmment and numbers-at-age are initialized in the first historical year using the SRA model (Appendix \@ref(app:sra), Equations \@ref(eq:om-sra-numinit) and \@ref(eq:om-sra-recinit)).

During the projection period (years $y$ = $t_{c+1}$ to $y$ = $t_N$), the number of fish recruited to the first age group in each year $N_{y,a=1}$
is calculated as a function of last year's spawning biomass \(B_{y-1}\), assuming a Beverton-Holt stock-recruit relationship [@beverton1957] with annual
lognormal recruitment deviations $\varepsilon_{R,y-1}$:

\begin{equation}
N_{y, a = 1} = \left( \frac{4 {h} R_{0} B_{y-1}} {B_{0}  \left( 1 - {h} \right) + \left( 5{h} - 1 \right) B_{y-1}} \right) \cdot \varepsilon_{R,y-1},
(\#eq:dlm-om-recy)
\end{equation}

where unfished spawning biomass \(B_{0}\) is calculated as the
sum over ages of the maturity at age $m_a$, weight-at-age
$W_a$, and unfished numbers at age  \({{\ {R}}_{0}\ e^{\sum_{i = 1}^{a}M_{i}}}\):

\begin{equation}
B_{0} = \sum_{a = 1}^{n_{a}}{m_{a}\ W_{a}{\ {R}}_{0}\ e^{\sum_{i = 1}^{a}M_{i}}}.
(\#eq:dlm-om-bo)
\end{equation}

and spawning biomass $B_{y}$ in a given year is the
sum over ages of the maturity-at-age $m_a$, the weight-at-age
$W_a$, and numbers at age $N_{y,a}$:

\begin{equation}
B_{y} = \sum_{a = 1}^{n_{a}}{m_{a}W_{a}N_{y,a}}.
(\#eq:dlm-om-sy)
\end{equation}

Annual recruitment deviations ($\varepsilon_{R,y}$) are generated by first sampling from a lognormal distribution with mean $1$ and standard deviation \({{\sigma}}_{R}\):

\begin{equation}
\varepsilon_{R,y}\sim \mathrm{Lognormal}\left( 1,{{\sigma}}_{R} \right),
(\#eq:dlm-om-recdev)
\end{equation}

Temporal autocorrelation \({{\theta}}_{\textrm{AC}}\) is added to these initial draws ($\varepsilon_{R,y}$) as:

\begin{equation}
\varepsilon_{R,y} = {{\theta}}_{\textrm{AC}}\varepsilon_{R,y - 1} + \varepsilon_{R,y}\sqrt{\left( 1 - {{{\theta}}_{\textrm{AC}}}^{2} \right)},
(\#eq:dlm-om-auto)
\end{equation}

where $\theta_{\mathrm{AC}}$ represents a first-order autocorrelation term, and setting \({{\theta}}_{\textrm{AC}}\) to zero implies no autocorrelation.

The number of fish $N$ in each year $y$ > $t_c$ and age $a$ > 1 is then calculated from the numbers in the previous year and age class,
subject to the instantaneous total mortality rate ($Z$) at age ($a$):

\begin{equation}
N_{y + 1,a + 1} = N_{a}e^{- Z_{a}} 
(\#eq:dlm-om-numa)
\end{equation}

where the total mortality rate $Z_{y,a}$ is the sum of the instantaneous rates of natural mortality ($M$), assumed constant across years and ages unless otherwise specified, and fishing mortality-at-age ($F_{y,a}$, defined in Equation \@ref(eq:dlm-om-Fay)):

\begin{equation}
Z_{y,a} = M + F_{y,a}v_{y,a}.
(\#eq:dlm-om-z)
\end{equation}

where v_{y,a} is vulnerability-at-age, defined in Equation \@ref(eq:dlm-om-vay).

## FLEET DYNAMICS {#sec:dlmtool-fleet-dynamics}

Parameters for the fleet dynamics are included in the `Fleet` object of DLMtool.
During the projection period, the rate of fishing mortality-at-age ($F_{y,a}$) is calculated from the TAC prescribed by the MP ($\textrm{TAC}_{\mathrm{MP},y}$).
To distribute catches over ages it is first necessary to calculate the distribution of vulnerable biomass across ages ($V_{y,a}$):

\begin{equation}
V_{y,a} = N_{y,a} W_{a} v_{a} R_{a}
(\#eq:dlm-om-vulcom)
\end{equation}

where the vulnerability-at-age  $v_{y,a}$ is calculated from a double-normal selectivity curve and length-at-age:

\begin{equation}
v_{y,a} = \left\{ \begin{matrix} 
2^{- \ \frac{{(L_{y,a} - {{L}}_{\textrm{smax}})}^{2}}{\sigma_{\textrm{sasc}}^{2}}} & L_{y,a} \leq {{L}}_{\textrm{smax}} \\ 
2^{- \ \frac{{(L_{y,a} - {{L}}_{\textrm{smax}})}^{2}}{\sigma_{\textrm{sdesc}}^{2}}} & L_{y,a} > {{L}}_{\textrm{smax}} \\ 
\end{matrix} \right.\ 
(\#eq:dlm-om-vay)
\end{equation}

<!-- The length at maximum selectivity \(L_{\textrm{smax}}\) is user-defined.  -->
The standard deviation parameters of the ascending limb are given by the length at 5% vulnerability \({L}_{5}\):

\begin{equation}
\sigma_{\textrm{sasc}}^{2} = \frac{{{L}}_{5} - {{L}}_{\textrm{smax}}}{\sqrt{- \log_{2^{0.05}}}}
(\#eq:dlm-om-siglasc)
\end{equation}

While the standard deviation of the descending limb is given by the vulnerability \({V}_{\overline{L}} \) of fish of length \(\overline{L}\):

\begin{equation}
\sigma_{\textrm{sdesc}}^{2} = \frac{\overline{L} - {{L}}_{\textrm{smax}}}{\sqrt{- \log_{2^{{{V}}_{\overline{L}}}}}}
(\#eq:dlm-om-sigldes)
\end{equation}

The realized projected catches $C_{y,a}$ are the TAC recommendations across ages. 
Projected catches may account for retention rate ($R_{y,a}$) and post-release discard mortality rate $\theta_{M{\textrm{disc}}}$ in the presence of discarding.
Implementation uncertainty ($I_\textrm{TAC}$, Equation \@ref(eq:dlm-om-itac)) may also be accounted for, e.g., in the presence of consistent under-utilization of TACs. 

\begin{equation}
C_{y,a} = \frac{V_{y,a}} {\sum_{a}^{n_{a}}V_{y,a}}
\textrm{TAC}_{\mathrm{MP},y}\ I_{\mathrm{TAC},y}\
\frac{R_{y,a} + \left( 1 - R_{a} \right)
{{\theta}}_{\textrm{Mdisc}}}{R_{a}}
(\#eq:dlm-om-cata)
\end{equation}

where ($I_\textrm{TAC}$) is user-defined, and the overall retention rate-at-age $R_a$, is a combination of an age-specific retention $r_{y,a}$ with a maximum value of $1$ (Equation \@ref(eq:dlm-om-ray)), and a constant rate of discarding \(\gamma\):

\begin{equation}
R_{a} = r_{a}\ (1 - \gamma).
(\#eq:dlm-om-retention)
\end{equation}

where age-specific retention $r_{y,a}$, is modelled using the same form of double-normal curve as selectivity:

\begin{equation}
r_{y,a} = \left\{ \begin{matrix} 
2^{- \ \frac{{(L_{y,a} - {{L}}_{\textrm{rmax}})}^{2}}{\sigma_{\textrm{rasc}}^{2}}} & L_{y,a} \leq {{L}}_{\textrm{rmax}} \\ 
2^{- \ \frac{{(L_{y,a} - {{L}}_{\textrm{rmax}})}^{2}}{\sigma_{\textrm{rdesc}}^{2}}} & L_{y,a} > {{L}}_{\textrm{rmax}} \\ 
\end{matrix} \right.\ 
(\#eq:dlm-om-ray)
\end{equation}

The length at maximum retention \({L}_{\textrm{rmax}}\) is
user-specified. The standard deviation parameters of the
ascending limb is given by user-specified length at 5% retention
\({r}_{5}\):

\begin{equation}
\sigma_{\textrm{rasc}}^{2} = \frac{{{r}}_{5} - {L}_{\textrm{rmax}}}{\sqrt{- \log_{2^{0.05}}}}
(\#eq:dlm-om-sigrasc)
\end{equation}

While the standard deviation of the descending limb is given by
user-specified retention \({{r}}_{\overline{L}} \) of fish of
length \(\overline{L}\):

\begin{equation}
\sigma_{\textrm{rdesc}}^{2} = \frac{\overline{L} - {{L}}_{\textrm{rmax}}}{\sqrt{- \log_{2^{{{r}}_{\overline{L}}}}}}
(\#eq:dlm-om-sigrdec)
\end{equation}

Fishing mortality rates are then calculated from the realized catches $C_{y,a}$
subject to the constraint that they do not exceed user-specified
${F_\textrm{max}}$:

\begin{equation}
F_{y,a} = \min \left( - \ln\left( 1 - \frac{C_{y,a}}{N_{y,a}{W}_{a}} \right),F_{\max} \right).
(\#eq:dlm-om-Fay)
\end{equation}


## OBSERVATION DYNAMICS

Parameters for observation dynamics are included in the `Obs` object of DLMtool.
The observation dynamics emulate the collection of data for use in the MPs.
Two fundamental types of data are simulated by the OM: (1) time series data (e.g. annual
catches from 1970-2017); and (2) catch composition data (e.g., length or age samples).

### Time series data

Time series data are simulated with various types of error that would be expected from real-life sampling of fisheries data (e.g., lognormal observation error in indices of abundance). 

Annual observed indices of abundance are calculated by adding observation error and bias to annual relative total biomass ($B_{y}$) through a
factor term $\omega_{I,y}$ that includes bias and imprecision in the index observations:

\begin{equation}
I_{y}^{\text{obs}} = \omega_{I,y}\frac{{B_{y}}^{\beta}}{\frac{1}{y}\sum_{i = 1}^{y}{B_{i}}^{\beta}}
(\#eq:dlm-om-iy)
\end{equation}

where $B^T_{y}$ is total biomass given by the sum over ages of the weight-at-age $W_a$, and numbers at age $N_{y,a}$:

\begin{equation}
B^T_{y} = \sum_{a = 1}^{n_{a}}{W_{a}N_{y,a}}
(\#eq:dlm-om-by)
\end{equation}

and where $\beta$ is the hyperstability-hyperdepletion parameter. When $\beta$ is 1
the index is linearly related to spawning biomass $S_y$. When $\beta$ is
greater than 1 the index is hyper deplete and moves faster than true
spawning biomass changes. When $\beta$ is lower than 1 the index is
hyperstable and moves slower than true spawning biomass changes. Note
that in every year $y$ that the index is recalculated, it is
re-normalised to have a mean value of 1 over all years.

The index factor $\omega_{I,y}$ represents imprecision in observations via ${\widetilde{\sigma}}_{I}$ .

\begin{equation}
\omega_{I,y} = \text{exp}\left( \varepsilon_{I,y} - \frac{{\widetilde{\sigma}}_{I}}{2} \right)
(\#eq:dlm-om-omegai)
\end{equation}

where the lognormal error term $\epsilon$, is drawn from a standard normal
distribution whose standard deviation ${\widetilde{\sigma}}_{I}$ is
sampled at random in each simulation:

\begin{equation}
\varepsilon_{I,y}\sim N\left( 0,{\widetilde{\sigma}}_{I} \right)
(\#eq:dlm-om-epsiloni)
\end{equation}

By default DLMtool samples simulation-specific observation error
${\widetilde{\sigma}}_{I}$ from a uniform distribution.

<!--TODO: the above text will need to be modified to reflect that sigma comes from conditioning in the SRA. Still to determine whether it will come from historical observed index or from residuals in SRA fit to historical observed index-->

\begin{equation}
{\widetilde{\sigma}}_{I}\sim U\left( \text{LB}_{I},\text{UB}_{I} \right)
(\#eq:dlm-om-sigi)
\end{equation}.

This approach means that the user can specify a time series with a low degree of error (e.g., low sampled values
of ${\widetilde{\sigma}}_{I}$ specified by lower *LB~I~* and *UB~I~*), or
a large degree of error (e.g., large sampled values of
${\widetilde{\sigma}}_{I}$ specified by higher *LB~I~* and *UB~I~*).


### Catch composition data

<!-- TODO: I don't think we use CAL anywhere. If so can simplify the description below to be only in terms of CAA because we haven't anywhere defined how CAL is generated by the model-->

Two types of catch composition observations are simulated, catches by
age class by year (CAA) and catches by length class by year (CAL).

These observation models use a simple multinomial model that accounts
for effective sample size (the number of independent observations). 
For both CAA and CAL observation models the user specifies an average annual
number of samples (number of individuals measured for example) and the
annual effective sample size($C_{y,a}^{\text{obs}}$ or $C_{y,l}^{\text{obs}}$). 
For example, $ESS_{CAA}$ independent catch
samples-at-age (e.g. 20 per year) are sampled in proportion $p$ to the
catches-at-age predicted by the model ($C_{y,a}$, Equation \@ref(eq:dlm-om-cata)):

\begin{equation}
C_{y,a}^{\text{obs}}\sim multinomial\left( \text{ESS}_{\text{CAA}},p_{a} = \ \sum_{r}^{n_{r}}C_{y,a,r} \right)
(\#eq:dlm-om-cataobs)
\end{equation}

For each year, the frequency of samples at age is inflated to match the
total sample size $n~CAA~$ and rounded to the nearest integer:

\begin{equation}
C_{y,a}^{\text{obs}} = nint\left( \ \frac{{\dot{C}}_{y,a}^{\text{obs}}\ n_{\text{CAA}}}{\text{ESS}_{\text{CAA}}} \right)
(\#eq:dlm-om-cataobs-freq)
\end{equation}

Due to rounding, this relatively simple model generates frequency-at-age
data that are approximately equal to the average
annual sample size:

\begin{equation}
\sum_{a}^{n_{a}}{C_{y,a}^{\text{obs}}\ } \approx n_{\text{CAA}}
(\#eq:dlm-om-cataobs-equality)
\end{equation}

## IMPLEMENTATION DYNAMICS

Parameters for implementation dynamics are included in the `Imp` object of DLMtool.
DLMtool includes three types of implementation error, which relate to MPs that provide management advice in terms of Total Allowable Catch (TAC), Total Allowable Effort (TAE) and size limits (SL). 
This Framework only considers MPs that provide TAC advice for its quota-managed groundfish fishery.
Given that BC groundfish fisheries are subject to 100% at-sea and dockside observer coverage, we make the assumption that under-reporting of TACs is negligible. 
However, for non-target species, there is a possibility that TACs will not be fully-utilized. 
The implementation uncertainty in TACs is applied in Equation \@ref(eq:dlm-om-cata). 

The TAC implementation uncertainty term ($I_\textrm{TAC}$) is the product of a constant fraction of the TAC taken ${\widetilde{b}}_{\text{TAC}}$ and a degree of inter-annual
variability controlled by ${\widetilde{\sigma}}_{\text{TAC}}$.


\begin{equation}
I_{TAC,y} = {\widetilde{b}}_{\text{TAC}}\text{\ exp}\left( \varepsilon_{TAC,y} - \frac{{\widetilde{\sigma}}_{\text{TAC}}}{2} \right)
(\#eq:dlm-om-itac)
\end{equation}


where ${\widetilde{b}}_{\text{TAC}}$ is an improper fraction (e.g.
${\widetilde{b}}_{\text{TAC}}$ = 0.7 is equivalent to 30% catch
underages) and the lognormal error term $\varepsilon_{TAC,y}$, is drawn from a standard
normal distribution whose standard deviation
${\widetilde{\sigma}}_{\text{TAC}}$ was sampled at random in each
simulation:

\begin{equation}
\varepsilon_{TAC,y}\sim N\left( 0,{\widetilde{\sigma}}_{\text{TAC}} \right)
(\#eq:dlm-om-epsilontac)
\end{equation}

By default DLMtool samples simulation-specific variability
${\widetilde{\sigma}}_{\text{TAC}}$ from a uniform distribution.

\begin{equation}
{\widetilde{\sigma}}_{\text{TAC}}\sim U\left( \text{LB}_{\text{TAC}},\text{UB}_{\text{TAC}} \right)
(\#eq:dlm-om-sigmatac)
\end{equation}

and mean fraction of recommendation ${\widetilde{b}}_{\text{TAC}}$ from
a log-normal distribution:

\begin{equation}
{\widetilde{b}}_{\text{TAC}} = \ exp\left( \varepsilon_{\text{bTAC}} - \frac{\sigma_{\text{bTAC}}}{2} \right)
(\#eq:dlm-om-btac)
\end{equation}

\begin{equation}
\varepsilon_{\text{bTAC}}\sim N\left( 0,\sigma_{\text{bTAC}} \right)
(\#eq:dlm-om-epsilonbtac)
\end{equation}

## CALCULATION OF MSY-BASED REFERENCE POINTS

Biological reference points (BRPs) in the MP Framework are currently based on the provisional reference points recommended in Canada's PA Framework [@dfo2006; @dfo2009], where the limit reference point (LRP) is defined as the OM value of $0.4B_\text{MSY}$ and the Upper Stock Reference (USR) is defined as the OM value of $0.8B_\text{MSY}$.
$B_\text{MSY}$ is defined as the equilibrium spawning biomass $B^e$ that would occur if the stock were fished at the constant rate of fishing mortality $F^e$ that produces maximum sustainable yield $\text{MSY}$.

Calculation of BRPs is done using estimated parameters from the conditioning stage, described in Appendix \@ref(app:sra). 
In the absence of annual variability in life history and/or selectivity parameters, $F_\text{MSY}$ is calculated by numerically solving for the value of equilibrium $F^e$ that maximizes the equilibrium yield $Y^e$

\begin{equation}
Y^e = F^e R^e \phi_f
(\#eq:dlm-om-yeq)
\end{equation}

where $R^e$ is equilibrium recruitment (Equation \@ref(eq:dlm-om-req)) and $\phi_f$ is equilibrium spawning biomass-per-recruit, defined in Equation \@ref(eq:dlm-om-phif) below.

In this framework, we assume a Beverton-Holt stock-recruit relationship [@beverton1957], although DLMtool also allows users to select the Ricker form [@ricker1954]:

\begin{equation}
R^e = 
\begin{cases}
      \dfrac{\alpha^{\textrm{B}}\phi_f - 1}{\beta^{\textrm{B}}\phi_f} & \textrm{Beverton-Holt}\\
      \dfrac{\log(\alpha^{\textrm{R}}\phi_f)}{\beta^{\textrm{R}}\phi_f} & \textrm{Ricker}
\end{cases}
(\#eq:dlm-om-req)
\end{equation}

where $\alpha^{\textrm{B}}$ and $\beta^{\textrm{B}}$ are the parameters of the Beverton-Holt stock recruit relationship, and $\alpha^{\textrm{R}}$ and $\beta^{\textrm{R}}$ are the parameters of the Ricker stock recruit relationship,  derived from user-defined parameters steepness ($h$) and $R_0$, where
$\alpha^{\textrm{B}} = \frac{4h}{(1-h)\phi_e}$, 
$\beta^{\textrm{B}} = \frac{5h-1}{(1-h)B_0}$
and
$\alpha^{\textrm{R}} = \frac{(5h)^{1.25}}{\phi_e}$,
$\beta^{\textrm{R}} = \frac{\log(5h)}{B_0}$, 
where $B_0$ is unfished spawning biomass, derived from $R_0$ (Equation \@ref(eq:dlm-om-bo)), and $\phi_e$ is unfished spawning biomass-per-recruit defined by setting $F^e=0$ in Equation \@ref(eq:dlm-om-phif).

Equilibrium spawning biomass-per-recruit is calculated

\begin{equation}
\phi_f = \sum_{a=1}^A \iota_a W_a m_a
(\#eq:dlm-om-phif)      
\end{equation}

where $\iota_a$ is equilibrium survivorship-at-age:

\begin{equation}
   \iota_a=
      \begin{cases} 
            1, & a=1 \\                
            \iota_{a-1}e^{-Z^e_{a-1}}, & 1<a<A \\
            \dfrac{\iota_{a-1}e^{-Z^e_{a-1}}}{1-e^{-Z^e_{a}}} , & a=A\\
      \end{cases}
(\#eq:dlm-om-survivorship)      
\end{equation}

where $Z^e_{a}$ is equilibrium total mortality-at-age: 

\begin{equation}
Z^e_{a} = M +  F^e_{a}v_{a}
(\#eq:dlm-om-zeq)      
\end{equation}

<!--TODO: do we want to explain how DLMtool numerically solves for FMSY (e.g., Newton-Raphson algorithm or just leave it vague)? My preference is to leave it vague. there are lots of ways to do it and the details aren't really important as long as it works.-->

After numerically solving Equation \@ref(eq:dlm-om-yeq) for $F_\text{MSY}$, $B_\text{MSY}$ is simply calculated:

\begin{equation}
B_{\text{MSY}} = \phi_f R^e
(\#eq:dlm-om-bmsy)      
\end{equation}

with $F^e=F_\text{MSY}$ in Equation \@ref(eq:dlm-om-survivorship).

<!-- TODO: Do we want to say anything about cases where parameters are time-varying? The DLmtool guide mentions it. I would suggest leaving it out, as we might choose to do it a different way anyway if the FSERP project identifies a best approach ... -->

