\clearpage

# MSETOOL STOCK REDUCTION ANALYSIS {#app:sra}

<!--
**The following is preliminary and largely reproduced from an MSEtool vignette (written by Quang Huynh) for completeness with some modifications. Updated by QH and imported by RF Feb 14 2020**

**The text before the equations will be rewritten for the purposes of this document.**
-->

## A BACKGROUND ON STOCK REDUCTION ANALYSIS {#sec:sra-background}

The operating model (OM) defined in Appendix \@ref(app:dlmtool-om) is conditioned  by fitting an age-structured stock-reduction analysis (SRA) [@kimura1982; @walters2006] to historical observed catches and indices of abundance (and to age- and length-composition data if available).
This step produces estimates of parameters that are conditioned to produce time-series trajectories consistent with historical observations.
This is especially important in data-limited or data-moderate situations, where the lack of an accepted assessment makes it difficult to parameterize historical depletion and fishing mortality $F$.

In the literature, the term "stock reduction analysis" has been used to describe a model in which the predicted total catch matches the observed catch.
@kimura1982 presented SRA as an alternative to a virtual production analysis (VPA) or surplus production model.
The SRA approach is more applicable to data-limited species than, for example, a VPA when annual catch-at-age data are not available, while also using an age-structured modeling approach that incorporates natural mortality and recruitment information for reconstructing the stock history, rather than taking a pooled biomass-dynamics approach (e.g., surplus production model).
Another advantage of the SRA approach for BC groundfish fisheries is it accommodates conditioning on multiple indices of abundance (e.g., accommodating indices from multiple fishery-independent surveys and/or commercial CPUE series).

For data-limited species, where it may only be possible to provide ranges of values for key parameters, the SRA approach tries to reduce the range of plausible parameters to be consistent with historical observations.
In other words, it helps address the broader question:
What combinations of historical fishing mortality and recruitment could have generated the observed data [@walters2006]?

## STOCK REDUCTION ANALYSIS IN THE CONTEXT OF DLMTOOL {#sec:sra-dlmtool}

The SRA described here can be fit with the R package MSEtool via the function `SRA_scope()`.
The function takes a DLMtool OM object (Appendix \@ref(app:dlmtool-om)) and historical observed data (observed catches, indices of abundance and, if available, composition data), fits the SRA to the observed data, and returns a list with an updated OM and calibrated outputs from the SRA.

The approach can be stochastic (with Monte Carlo sampling) if the operating model is specified with ranges on key parameters.
For example, the steepness parameter of the stock-recruit relationship ($h$) is usually highly uncertain.
The initial OM can specify a range of values for $h$ (e.g., 0.6 to 0.9 with a uniform distribution):

$$
h \sim \textrm{Uniform} (0.6,0.9).
$$

In this case, with $i = 1$ to $n$ (e.g., $n = 250$) simulations in the closed-loop simulation, the SRA function will sample $n$ steepness values from this distribution and fit the SRA model $n$ times.
The SRA model reconstruction from the $i^{\textrm{th}}$ fit will be conditioned on the $i^{\textrm{th}}$ sampled value of $h$.
The sampled values of $h$ (as well as all other input parameters to the SRA) are then saved alongside the estimated parameters to form the conditioned OM.

## THE STOCK REDUCTION ANALYSIS MODEL {#sec:sra-model}

The SRA model can be conditioned on catch or fishing effort.
For BC groundfish species, we recommend conditioning the model on catch.
If the model is conditioned on catch, then the SRA will generate predicted catches that match the observed catches.
<!--If conditioned on effort, the estimated fishing mortality in the model will be proportional to the observed effort.-->
A full time series of the conditioning variable (i.e., catch) is required needed.
<!--, and length of the historical period `OM@nyears` will be the length of the conditioned time series.-->

In many cases, the time series can be assumed to begin at unfished conditions ($B_{t=1} = B_0$, where $B_{t=1}$ is spawning biomass in the first historical year and $B_0$ represents equilibrium stock size in unfished conditions).
However, for some BC groundfish species, catch records may be less reliable prior to the introduction of comprehensive catch monitoring (e.g., in 1996 for the BC groundfish trawl fleet).
In these cases, the SRA model is set up such that a value for equilibrium catch ($C_\textrm{eq}$) prior to the first year of the catch time series can be assumed.
The SRA will then use this value to estimate the initial depletion ($\frac{B_{t=1}}{B_0}$) in the first year of the historical period.
However, even using this approach, initial depletion is difficult to estimate with precision without other sources of information (e.g., a long index of abundance, or age-composition data).
We therefore recommend treating $C_\textrm{eq}$ as a major axis of uncertainty if this approach is taken.
An alternative approach is to use catch-reconstruction methods [e.g., @porch2004; @starr2017] to reconstruct the catch time series back to the time when the stock was considered unfished.
While this approach avoids the uncertainty associated with estimating depletion based on $C_\textrm{eq}$, it may introduce other sources of uncertainty associated with the reconstruction approach.

In addition to the conditioning time series, additional data types can be used, which do not need to be available in every year of the historical time series:

- Time series of indices of abundance (either as surveyed biomass or fishery-dependent CPUE);
- Age-composition data
- Length-composition data
- Mean length (in commercial or survey data)

<!--
The use of mean-length data is generally for very sparse data scenarios, when mean length data are available but there is no reliable composition data.
-->

Multiple surveys and fleets can be accommodated by the SRA.
Including one of these data types in addition to the conditioning catch time series is generally needed to inform depletion estimates.
Even in cases where availability of these data is sparse over time, they can still be informative for estimates of depletion.
For example, an age-composition sample from a single recent year that shows a very truncated age structure can imply a heavily depleted stock.
Age-composition data from one or a few years can also be informative about selectivity, which in turn informs estimates of stock size.

The required pre-specified OM parameters needed for SRA scoping are provided in Table **TODO**:

*TODO: turn this into a table with parameter symbols if applicable (I added these in square parentheses] and slots. Same format we will use in 07-dlmtool-om.rmd*

<!-- Note the following parameters in the list below have not been defined in the OM as far as I can tell. Should we add them to the OM documentation or remove them here?
OM@LenCV
OM@M2
Checking that OM@Perr = $\sigma_{R}$
OM@LFS
-->

- Growth (length-at-age) using DLMtool OM slots `OM@Linf, OM@K, OM@t0` (or alternatively, `OM@cpars$Len_age`) [$L_{\infty}$, $\kappa$, $a_{0}$]

- Length-weight conversion factors using slots `OM@a` and `OM@b` (or alternatively, `OM@cpars$Wt_age`) [$\alpha_{W}$, $\beta_{W}$]

- Natural mortality `OM@M`
<!-- or `OM@cpars$M_ageArray`[$M$] -->

- Maturity using slots `OM@L50, OM@L50_95` [$\theta_{l50}$, $\theta_{l50-95}$]
<!-- or `OM@cpars$Mat_age` -->

- Standard deviation of recruitment deviations using slot `OM@Perr`[$\sigma_{R}$]

- Stock-recruit relationship with `OM@SRrel` (Beverton-Holt or Ricker)

- Selectivity parameters with `OM@L5`, `OM@LFS`, and `OM@Vmaxlen`. If there are no age or length compositions, then selectivity in the model is fixed to these values. Otherwise, these are used as starting values. [$L_{5}$, $L_{LFS}$]

- Unfished recruitment `OM@R0` as the starting value [$R_0$].

*TODO: We have not talked about time-varying scenarios. Add a section in the DLMtool OM documentation*

If growth, natural mortality, or maturity are set to be time-varying in the historical period, then the SRA will implement time-varying life history in the estimation model as well.
Selectivity is fixed if no age or length compositions are provided.
Otherwise, the ascending limb of selectivity is estimated with age or length composition data.
If the selectivity is assumed to be dome-shaped, then the descending limb can either be fixed values sampled from slot `OM@Vmaxlen` or estimated in the SRA.

## Updated parameters and SRA model evaluation

*TODO: Consolidate this list with the parameters above. Add them all to the same table and indicate whether or not they are updated*

Historical OM parameters that are updated by the SRA scoping function include:

- Unfished recruitment `OM@R0` (when the model is conditioned on catch). [$R_0$]

- Depletion `OM@D` [$\frac{B_{t}}{B_0}$]

- Recruitment autocorrelation `OM@AC` which is estimated post-hoc from the recruitment deviation estimates. [$\theta_{\textrm{AC}}$]

- Annual recruitment deviations `OM@cpars$Perr_y`. Historical recruitment are those estimated from the model, while future recruitment will be sampled with autocorrelation. [$\sigma_{R}$]

- Selectivity parameters `OM@L5, OM@LFS, and OM@Vmaxlen`. If multiple fleets are modeled, then the F-at-age matrix is used to derive the effective selectivity and placed in `OM@cpars$V`. [$L_{5}$, $L_{LFS}$]

If initial depletion is estimated, then the annual recruitment deviations in the first year `OM@cpars$Perr_y` ($\varepsilon_{R,y}$) are adjusted in order to produce the estimated abundance-at-age in the first year of the SRA model (Equation \@ref(eq:sra-om-numinit)).

If multiple fleets are used for conditioning, then annual vulnerability-at-age ($v_{y,a,f}$, Equation \@ref(eq:sra-om-vyaf)) will be updated based on the relative fishing mortality among fleets.

*TODO: the sentence above is rather vague. Improve it and refer to equations where necessary (or consider deleting it)*

The default assumption in the projection period of the closed-loop simulation is that the selectivity and relative fishing mortality among fleets are identical to those in the last historical year $t_c$.

## DESCRIPTION OF THE SRA MODEL

### Vulnerability-at-age and mortality

Fleet-specific vulnerability-at-age ($v_{y,a,f}$) is length-based and modeled as a double-exponential function (using base 2).
For fleet $f$ with asymptotic vulnerability, a two-parameter logistic function is used, with parameters defining the length-of-5%-vulnerability ($L^5_f$) and the length-of-full-vulnerability $L^{\textrm{FS}}_f$.
For dome-shaped vulnerability, a third parameter, the vulnerability at $L_{\infty}$, $V^{L_{\infty}}_f$ is also used.
Length-based vulnerability is converted to age-based vulnerability in the age-structured model as:

$$
v_{y,a,f} =
\begin{cases}
2^{-[(L_{y,a} - L^{\textrm{FS}}_f)/(\sigma^{\textrm{asc}}_f)]^2} & \textrm{if } L_{y,a} < L^{\textrm{FS}}_f\\
1 & \textrm{if logistic and } L_{y,a} \ge L^{\textrm{FS}}_f,\\
2^{-[(L_{y,a} - L^{\textrm{FS}}_f)/(\sigma^{\textrm{des}}_f)]^2} & \textrm{if dome-shaped and } L_{y,a} \ge L^{\textrm{FS}}_f
\end{cases},
(\#eq:sra-om-vyaf)
$$

where $L_{y,a}$ is the mean length-at-age in year $y$, and $\sigma^{\textrm{asc}}_f = (L^5_f - L^{\textrm{FS}}_f)/\sqrt{-\log_2(0.05)}$ and $\sigma^{\textrm{des}}_f = (L_{\infty} - L^{\textrm{FS}}_f)/\sqrt{-\log_2(V^{L_{\infty}})}$ control the shape of the ascending and descending limbs, respectively, of the vulnerability function. In this parameterization, length-based vulnerability is constant over time. The corresponding age-based vulnerability is constant over time if growth is not time-varying.

Total mortality $Z$ in year $y$ and for age $a$ is given by

$$
Z_{y,a} = M_{y} + \Sigma_f v_{y,a,f} F_{y,f}
(\#eq:sra-om-zya)
$$

where $F_{y,f}$ is fishing mortality by year $y$ and fleet $f$, and $M_{y,a}$ is natural mortality in year $y$.


### Initial population distribution

The population age distribution in the first year of the model $y=1$ is in equilibrium:

$$
N_{1,a} =
\begin{cases}
      R^{\textrm{eq}} \exp(-\Sigma_{i=1}^{a-1}Z^{\textrm{eq}}_i) & a = 1, \ldots, A-1\\
      \dfrac{R^{\textrm{eq}} \exp(-\Sigma_{i=1}^{a-1}Z^{\textrm{eq}}_i)}{1 - \exp(-Z^{\textrm{eq}}_A)} & a = A,
\end{cases}
(\#eq:sra-om-numinit)
$$

where the $R^{\textrm{eq}}$ is the equilibrium recruitment and $Z^{\textrm{eq}}_a = M_{1,a} + \Sigma_f v_{1,a,f} F^{\textrm{eq}}_f$ is the equilibrium total mortality rate. Unfished conditions are modeled by setting $F^{\textrm{eq}}_f = 0$. To estimate $F^{\textrm{eq}}_f$, the corresponding equilibrium catch in weight $\tilde{C}^{\textrm{eq}}_f$ prior to the first year of the model should be provided. In the equilibrium yield curve,  $F^{\textrm{eq}}_f$ would be the fishing mortality corresponding to fishing at $F^{\textrm{eq}}_f$. Once $Z^{\textrm{eq}}_a$ is obtained, then the equilibrium recruitment is calculated as:

$$
R^{\textrm{eq}} =
\begin{cases}
      \dfrac{\alpha^{\textrm{B}}\phi^{\textrm{eq}} - 1}{\beta^{\textrm{B}}\phi^{\textrm{eq}}} & \textrm{if Beverton-Holt stock-recruit relationship}\\
      \dfrac{\log(\alpha^{\textrm{R}}\phi^{\textrm{eq}})}{\beta^{\textrm{R}}\phi^{\textrm{eq}}} & \textrm{if Ricker stock-recruit relationship},
\end{cases}
(\#eq:sra-om-recinit)
$$

where $\phi^{\textrm{eq}}$ is the spawners-per-recruit when the mortality is $Z^{\textrm{eq}}_a$. From steepness $h$, $\alpha^{\textrm{B}} = \frac{4h}{(1-h)\phi_0}$, $\beta^{\textrm{B}} = \frac{5h-1}{(1-h)B^S_0}$, $\alpha^{\textrm{R}} = \frac{(5h)^{1.25}}{\phi_0}$, $\beta^{\textrm{R}} = \frac{\log(5h)}{B^S_0}$, where $\phi_0$ and $B^S_0$ are unfished spawners-per-recruit and unfished spawning biomass, respectively.

### Dynamics equations

After setting the equilibrium population age distribution in the first year of the model, the population abundance $N_{y,a}$ in subsequent years is

$$
N_{y,a} =
\begin{cases}
      R_y & a = 1\\
      N_{y-1,a-1} \exp(-Z_{y-1,a-1}) & a = 2, \ldots, A - 1,\\
      N_{y-1,a-1} \exp(-Z_{y-1,a-1}) + N_{y-1,a} \exp(-Z_{y-1,a}) & a = A,
\end{cases}
(\#eq:sra-om-nya)
$$

where $R_y$ is the recruitment and $A$ is the maximum-age as the plus-group. Recruitment is modelled as

<!--TODO: change B^S to S-->

$$
R_y =
\begin{cases}
      \dfrac{\alpha^{\textrm{BH}} B^S_{y-1}}{1 + \beta^{\textrm{BH}}B^S_{y-1}} \exp(\delta_y - 0.5 \tau^2) & \textrm{if Beverton-Holt stock-recruit relationship}\\
      \alpha^{\textrm{Ricker}} B^S_{y-1} \exp(-\beta^{\textrm{Ricker}} B^S_{y-1})\exp(\delta_y - 0.5 \tau^2) & \textrm{if Ricker stock-recruit relationship},
\end{cases},
(\#eq:sra-om-rya)
$$

where $\delta_y$ are recruitment deviates and $\tau$ is the standard deviation of the deviates.

The spawning biomass is $B^S_y$ is

$$
B^S_y = \sum_a w_{y,a} m_{y,a} N_{y,a},
(\#eq:sra-om-sy)
$$

where $m_{y,a}$ and $w_{y,a}$ are the maturity-at-age and weight-at-age, respectively.

### Catch-at-age

If the model is fit to age-composition data, the catch (in numbers) $C^N$ at age for fleet $f$ is

$$
C^N_{y,a,f} = \dfrac{v_{y,a,f} F_{y,f}}{Z_{y,a}} N_{y,a} (1 - \exp[-Z_{y,a}]).
(\#eq:sra-om-cyaf)
$$

In our framework, we recommend conditioning the model on observed catches, as these are better reported than effort, and easier to interpret for a multispecies fishery.
In this case, with a model conditioned on catch, then $F_{y,f}$ can be estimated as parameters or solved iteratively to match the observed catch.
In other applications, if the model is conditioned on effort, then

$$
F_{y,f} = q_f E_{y,f},
(\#eq:sra-om-fyf-eff)
$$

where $E_{y,f}$ is the observed effort and $q_f$ is the scaling coefficient.

### Catch-at-length

If the model is fit to length-composition data, the catch-at-length is calculated assuming a normally distributed length-at-age $P(\ell,a)$, where


$$
C^N_{y,\ell,f} = \sum_a C^N_{y,a,f} P(\ell \vert a),
(\#eq:sra-om-cylf)
$$

and

$$
P(\ell \vert a) =
\begin{cases}
      \phi(L'_{\ell+1}) & \ell = 1\\
      \phi(L'_{\ell+1}) - \phi(L'_\ell) & \ell = 2, \ldots, L - 1,\\
      1 -\phi(L'_\ell) & \ell = L,
\end{cases}
(\#eq:sra-om-pla)
$$

where $L'_{\ell}$ is the length at the lower boundary of length bin $\ell$ and $\phi(L'_{\ell})$ is the cumulative distribution function of a normal variable with mean $\tilde{L}_{y,a}$ (the expected mean length at age $a$) and standard deviation $\tilde{L}_{y,a} \times CV^L$ ($CV^L$ is the coefficient of variation in mean length at age).

The catch in weight $\tilde{C}$ is

$$
\tilde{C}_{y,f} = \sum_a C^N_{y,a,f} w_{y,a}.
(\#eq:sra-om-cyfw)
$$

The mean length of the catch $\bar{L}_{y,f}$ is

$$
\bar{L}_{y,f} = \dfrac{\sum_{\ell} L_{\ell} C^N_{y,\ell,f}}{\sum_{\ell} C^N_{y,\ell,f}},
(\#eq:sra-om-lmean)
$$

where $L_\ell$ is the midpoint of the length bin $\ell$.

The proportion of the catch-at-age is

$$
p_{y,a,f} = \dfrac{C^N_{y,a,f}}{\sum_a C^N_{y,a,f}}.
(\#eq:sra-om-pyaf)
$$

The proportion of the catch-at-length is

$$
p_{y,\ell,f} = \dfrac{C^N_{y,\ell,f}}{\sum_{\ell}C^N_{y,\ell,f}}.
(\#eq:sra-om-pylf)
$$

## Survey

If the $s^{\textrm{th}}$ survey is biomass-based, then the survey value $I_{y,s}$ is calculated as

$$
I_{y,s} = q_s \sum_a v_{y,a,s} N_{y,a} w_{y,a},
(\#eq:sra-om-iysb)
$$

where $q$ is the scaling coefficient and $s$ indexes survey.

If the survey is abundance-based, then

$$
I_{y,s} = q_s \sum_a v_{y,a,s} N_{y,a}.
(\#eq:sra-om-iysn)
$$

### Likelihoods

If the model is conditioned on catch and fishing mortality rates are estimated parameters, then the log-likelihood component $\Lambda_1$ of the catch is

$$
\Lambda_1 = \sum_f \left[\lambda^{\tilde{C}}_f \sum_y \left(-\log(0.01) - \dfrac{[\log(\tilde{C}^{\textrm{obs}}_{y,f}) - \log(\tilde{C}^{\textrm{pred}}_{y,f})]^2}{2 \times 0.01^2}\right)\right],
(\#eq:sra-om-like-catch)
$$

where $\textrm{obs}$ and $\textrm{pred}$ indicate observed and predicted quantities, respectively, and $\lambda$ are likelihood weights. With a small standard deviation for the catch likelihood relative to the variance in other likelihood components, the predicted catch should match the observed catch.

The log-likelihood component $\Lambda_2$ of survey data is

$$
\Lambda_2 = \sum_s \left[ \lambda^I_s \sum_y \left(-\log(\sigma_{y,s}) - \dfrac{[\log(I^{\textrm{obs}}_{y,s}) - \log(I^{\textrm{pred}}_{y,s})]^2}{2\sigma_{y,s}^2}\right) \right].
(\#eq:sra-om-like-ind)
$$

The log-likelihood component $\Lambda_3$ of catch-at-age data is

$$
\Lambda_3 = \sum_f \lambda^A_f \left[\sum_y O^A_{y,f} \sum_a p^{\textrm{obs}}_{y,a,f} \log(p^{\textrm{pred}}_{y,a,f})\right],
(\#eq:sra-om-like-caa)
$$

where $O^A$ is the annual sample sizes for the age compositions.

The log-likelihood component $\Lambda_4$ of catch-at-length data is

$$
\Lambda_4 = \sum_f \lambda^L_f \left[ \sum_y O^L_{y,f} \sum_{\ell} p^{\textrm{obs}}_{y,\ell,f} \log(p^{\textrm{pred}}_{y,\ell,f})\right],
(\#eq:sra-om-like-cal)
$$

where $O^L$ is the annual sample sizes for the length compositions.

The log-likelihood component $\Lambda_5$ of observed mean lengths in the catch is

$$
\Lambda_5 = \sum_f \lambda^{\bar{L}}_f\left[ \sum_y \left(-\log(\omega_f) - \dfrac{[\bar{L}^{\textrm{obs}}_{y,f} - \bar{L}^{\textrm{pred}}_{y,f}]^2}{2 \omega^2_f}\right)\right],
(\#eq:sra-om-like-meanl)
$$

where $\omega_f$ is the standard deviation of mean lengths.

The log-likelihood component $\Lambda_6$ of annual estimated recruitment deviates $\delta_y$ in log space is

$$
\Lambda_6 = \Sigma_y\left(-\log(\tau) - \dfrac{\delta_y^2}{2 \tau^2}\right),
(\#eq:sra-om-like-recdevs)
$$

where $\tau$ is the standard deviation of recruitment deviates.

The log-likelihood component $\Lambda_7$ of the equilibrium catch is

$$
\Lambda_7 = \sum_f \lambda^{\tilde{C}}_f \left(-\log(0.01) - \dfrac{[\log(\tilde{C}^{\textrm{eq,obs}}_f) - \log(\tilde{C}^{\textrm{eq,pred}}_f)]^2}{2 \times 0.01^2}\right).
(\#eq:sra-om-like-eqcatch)
$$

The total log-likelihood $\textrm{LL}$ to be maximized is

$$
\textrm{LL} = \sum_{i=1}^7\Lambda_i
(\#eq:sra-om-like-tot)
$$

