---
title: "A management procedure framework for groundfish in British Columbia"
author: |
  Sean C. Anderson^1^,
  Robyn E. Forrest^1^,
  Chris J. Grandin^1^,
  Quang C. Huynh^2^,
  Elise A. Keppel^1^
author_list: "Anderson, S.C., Forrest, R.E., Grandin, C.J., Huynh, Q.C., Keppel, E.A."
address: |
  ^1^Pacific Biological Station\
     Fisheries and Oceans Canada, 3190 Hammond Bay Road\
     Nanaimo, British Columbia, V9T 6N7, Canada\
  ^2^Institute for the Oceans and Fisheries\
     University of British Columbia AERL, 2202 Main Mall\
     Vancouver, British Columbia, V6T 1Z4, Canada\
year: 2020
report_number: nnn
region: Pacific Region
abstract: |
  The Pacific Region Groundfish Integrated Fisheries Management Plan lists approximately 80 species-area fish stocks for which annual total allowable catches (TACs) are required, most of which are applied as individual transferable quotas (ITQs) within the British Columbia (BC) integrated groundfish fishery. The majority of fish stocks encountered by the integrated groundfish fishery are considered data-limited, where data-limited stocks are defined as those with insufficient data to reliably estimate stock status or estimate abundance or productivity with conventional stock assessment methods such as statistical catch-at-age models. In recent decades, DFO groundfish stock assessments have focused on data-rich stocks, resulting in a subset of stocks with full stock assessments, while many stocks with less informative data remain unassessed.

  The Department of Fisheries and Oceans (DFO) Sustainable Fisheries Framework, legislated via the Fish Stocks provisions in the *Fisheries Act*, requires that fish stocks be managed at sustainable levels---specifically at biomass levels above the Limit Reference Point (LRP). For data-limited stocks, data are often insufficient to adequately account for uncertainty in the assessment of stock status relative to biological reference points in traditional stock assessments. Instead of focusing on the explicit knowledge of current stock status, we propose a management-oriented approach that emphasizes selecting management procedures (MPs) that have a high likelihood of maintaining fish stocks above implicitly known reference points across multiple plausible states of nature, regardless of the quality and quantity of available data.

  Worldwide there has been a movement towards MP (or management strategy evaluation [MSE]) approaches to providing science advice on fish stocks via closed-loop simulation. Closed-loop simulation differs from conventional stock assessment because it simulates feedback between the implementation of MPs and a simulated system representing the fish stock and its environment, described by one or more operating models (OMs). This document presents a methodology for developing appropriate OMs, testing suites of MPs, and identifying MPs that best meet the objectives of fisheries management and stakeholders. We outline six best-practice steps for MP approaches: (1) defining the decision context, (2) setting objectives and performance metrics, (3) specifying OMs, (4) selecting candidate MPs, (5) conducting closed-loop simulations, and (6) presenting results to evaluate trade-offs. We then describe our proposed approach (the "MP Framework") and how it aims to accomplish each of these best-practice steps. Included in our framework are provisional conservation and fishery objectives and performance metrics based on Sustainable Fisheries Framework policies, a provisional library of data-limited MPs that are appropriate for BC groundfish stocks, and provisional visualizations to help decision-makers evaluate trade-offs amongst MPs.

  We undertake a case study of the Rex Sole (*Glyptocephalus zachirus*) stock in the West Coast Vancouver Island groundfish management area (Area 3CD) to demonstrate an application of the MP Framework. The case study develops six reference-set OMs and two robustness-set OMs. The case study reveals a set of survey-index-based MPs, constant catch, and surplus production MPs that achieve > 0.9 probability of maintaining biomass above the LRP in the long term (35--50-years in the future) while maintaining a high (> 0.8) probability of maintaining catches at or above recent (5-year) average levels in the near-term (1--10 years). We also present performance metrics related to the long-term probability of biomass remaining above the Upper Stock Reference, the long-term probability of fishing below *F*~MSY~ (fishing mortality at maximum sustainable yield), the long-term probability of maintaining catches above recent average levels, and the probability of catch variability remaining below historical levels. Four of the MPs achieved only slightly lower performance metrics in both robustness OMs, compared to the reference-set OMs, while other MPs were more sensitive to these robustness scenarios.

  We highlight issues regarding reference points, MP tuning, assessment frequency and triggers, the inclusion of environmental effects, assessing the value of information, and use of this framework as part of stock rebuilding plans. Throughout, our framework emphasizes transparency and reproducibility and to that end we develop an associated package for the software R that facilitates applications of the framework. Overall, we intend this framework to improve the capacity for Pacific DFO Science to provide evidence-based catch advice for more groundfish stocks---regardless of data limitations---in a standardized and transparent manner consistent with the DFO Sustainable Fisheries Framework, the Fish Stocks provisions in the *Fisheries Act*, and international best practices.
header: "Draft working paper --- Do not cite or circulate" # or "" to omit
output:
 csasdown::resdoc_pdf:
   french: false
# ------------
# End of options to set
knit: bookdown::render_book
link-citations: true
bibliography: refs.bib
csl: csl/csas.csl # or csl/csas-french.csl for French
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
# adjust as desired:
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = if (knitr:::is_latex_output()) "knitr-figs-pdf/" else "knitr-figs-docx/",
  cache.path = if (knitr:::is_latex_output()) "knitr-cache-tex/" else "knitr-cache-docx/",
  fig.asp = 0.618,
  fig.width = 7.5,
  out.width = "5in",
  echo = FALSE,
  autodep = TRUE,
  cache = TRUE,
  cache.comments = FALSE,
  dev = if (knitr:::is_latex_output()) "png" else "png",
  dpi = 180,
  fig.align = "center",
  fig.pos = "htb"
)
options(kableExtra.latex.load_packages = FALSE)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(gfplot)
library(gfutilities)
library(gfdlm)
library(csasdown)
library(DLMtool)
library(MSEtool)
library(rfishbase)
library(RColorBrewer)
library(tidyverse)
library(here)
filter <- dplyr::filter
options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(crop = NULL)
```
<!-- The math symbols greater and less than seem to render in RStudio Rmd files when inside $$..$$ chunks but tinytex doesn't recognize them unless the following are defined -->
\newcommand{\lt}{\ensuremath <}
\newcommand{\gt}{\ensuremath >}
