\newpage

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
if (!file.exists(here::here("generated-data", "rex-om-sra.rds"))) {
  source(here::here("sra/sra-data-rex.R"))
} 
```
  
  
<!-- # REX SOLE: MANAGEMENT PROCEDURE SPECIFICATIONS {#app:desc-mp-rex} -->

<!-- Use the management procedures that passed the screening test -->

```{r}
mprex <- c(
  "AvC",
  "CC2",
  "CC3",
  "DD",
  "DD4010",
  "GB_CC",
  "GB_target",
  "Islope1",
  "Islope2",
  "Islope4",
  "IT5",
  "ITM",
  "LstepCC2",
  "LstepCC3",
  "LstepCC4",
  "Ltarget1",
  "Ltarget2",
  "Ltarget3",
  "SBT2",
  "SP_4010",
  "SP_MSY"
)
```

# REX SOLE: RESULTS 

<!-- Get the operating model. For Shortraker we are using the DLMtool operating model. -->

```{r}
omrex <- readRDS(here::here("generated-data", "rex-om-sra.rds"))
```

<!-- How well does the SRA OM fit the indices? -->

```{r}
# rex_SRA_report <- readRDS(here::here("generated-data/rex-sra-report.rds"))
```

\newpage

<!-- Run the historical part of the MSE.  -->

```{r}
rex_historical <- runMSE(omrex, Hist = TRUE, parallel = FALSE)
```

```{r, fig.cap="Historical trajectories from the operating model"}
catch <- readRDS(here::here("generated-data", "rex-catch.rds"))
g1 <- gfdlm::plot_historical_ts(rex_historical, observed_ts = catch) +
  xlab("")
g2 <- gfdlm::plot_historical_ts(rex_historical, type = "SSB") +
  ylab("Historical SSB\n(spawning stock biomass)") +
  xlab("")
g3 <- gfdlm::plot_historical_ts(rex_historical, type = "Rec") +
  ylab("Historical recruitment\n(relative numbers)") +
  xlab("")
g4 <- gfdlm::plot_historical_ts(rex_historical, type = "Find") +
  ylab("Historical F\n(fishing mortality)") +
  xlab("")
cowplot::plot_grid(g1, g2, g3, g4, ncol = 2, align = "hv")
```

```{r}
file_name <- here::here("generated-data", "rex-mse.rds")
if (!file.exists(file_name)) {
  DLMtool::setup(cpus = parallel::detectCores())
  rex_mse <- runMSE(OM = omrex, MPs = mprex, parallel = TRUE)
  snowfall::sfStop()
  saveRDS(rex_mse, file = file_name)
} else {
  rex_mse <- readRDS(file_name)
}
# DLMtool::Converge(rex_mse)
```

```{r, fig.asp=1.2, out.width="4in", fig.width=6, fig.cap="Performance metric probability table."}
STY <- gfdlm:::pm_factory("LTY", 0.5, c(6, 20))
LTY <- gfdlm:::pm_factory("LTY", 0.5, c(36, 50))
PM <- c("P40_yrs36_50", "P80_yrs36_50", "STY", "LTY", "AAVY", "PNOF")
rex_probs <- gfdlm::get_probs(rex_mse, PM)
gfdlm::plot_probs(rex_probs)
```

```{r}
rex_satisficed <- dplyr::filter(rex_probs, P40_yrs36_50 >= 0.70) %>% pull(MP)
```

```{r}
rex_mse_sub <- DLMtool::Sub(rex_mse, MPs = rex_satisficed)
```


```{r, fig.asp=0.9, fig.cap="Timeseries projections."}
gfdlm::plot_projection_ts(rex_mse_sub, type = c("F_FMSY", "B_BMSY"))
```


```{r, fig.cap="Kobe plots"}
gfdlm::plot_contours(rex_mse_sub, xlim = c(0, 4), ylim = c(0, 4))
```

```{r, fig.cap="Spider plots", out.width="4.5in"}
gfdlm::spider(rex_mse_sub, pm_list = PM, palette = "Set2")
```

